name: check-build
on:
  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]

jobs:
  build-main:
    name: build-main
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go
    - name: Checkout
      uses: actions/checkout@v2
    - name: tidy
      run: go mod tidy
    - name: vet
      run: go vet
    - name: test
      run: go test
    - name: build
      run: env GOOS=linux GOARCH=amd64 go build
  build-client:
    name: build-client
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.13
        uses: actions/setup-go@v1
        with:
          go-version: 1.13
        id: go
      - name: Checkout
        uses: actions/checkout@v2
      - name: tidy
        run: cd client;go mod tidy
      - name: vet
        run: cd client;go vet
      - name: test
        run: go test --coverprofile coverage.txt
      - name: Upload Coverage report to CodeCov
        uses: codecov/codecov-action@v1.0.0
        with:
          token: ${{secrets.CODECOV_TOKEN}}
          file: ./coverage.txt
      - name: build
        run: cd client;env GOOS=linux GOARCH=amd64 go build

