name: release
on:
  release:
    types: [published]

jobs:
  release-image:
    name: release docker image
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.13
        uses: actions/setup-go@v1
        with:
          go-version: 1.13
        id: go
      - name: Checkout
        uses: actions/checkout@master
      - name: Get current release
        id: previoustag
        uses: "WyriHaximus/github-action-get-previous-tag@master"
        env:
          GITHUB_TOKEN: "${{ secrets.gh_token }}"
      - name: Set env
        run: echo ::set-env name=RELEASE_VERSION::${{ steps.previoustag.outputs.tag }}
      - name: build
        run: env GOOS=linux GOARCH=amd64 go build -o executable
      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: luckylukas/whenthengo
          username: ${{ secrets.docker_username }}
          password: ${{ secrets.docker_token }}
          tags: "latest,${{ env.RELEASE_VERSION }},client/${{ env.RELEASE_VERSION }},types/${{ env.RELEASE_VERSION }},cleaningpipe/${{ env.RELEASE_VERSION }},client/latest,types/latest,cleaningpipe/latest"
      - name: integrationtest-image
        run: go test -tags integration
      - name: build-client
        run: cd client;env GOOS=linux GOARCH=amd64 go build -o executable
      - name: integrationtest-client
        run: cd client;go test -tags integration

